In [669]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [670]:
plt.style.use("seaborn-muted")
%matplotlib inline
pd.set_option('display.max_columns', None)

In [671]:
banco = pd.read_csv("Training_Dataset_v2.csv", low_memory = False)

In [672]:
banco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1687861 entries, 0 to 1687860
Data columns (total 23 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   sku                1687861 non-null  object
 1   national_inv       1687860 non-null  float64
 2   lead_time          1586967 non-null  float64
 3   in_transit_qty     1687860 non-null  float64
 4   forecast_3_month   1687860 non-null  float64
 5   forecast_6_month   1687860 non-null  float64
 6   forecast_9_month   1687860 non-null  float64
 7   sales_1_month      1687860 non-null  float64
 8   sales_3_month      1687860 non-null  float64
 9   sales_6_month      1687860 non-null  float64
 10  sales_9_month      1687860 non-null  float64
 11  min_bank           1687860 non-null  float64
 12  potential_issue    1687860 non-null  object
 13  pieces_past_due    1687860 non-null  float64
 14  perf_6_month_avg   1687860 non-null  float64
 15  perf_12_month_avg  1687860 non-null  float64
 16  local_bo_qty       1687860 non-null  float64
 17  deck_risk          1687860 non-null  object
 18  oe_constraint      1687860 non-null  object
 19  ppap_risk          1687860 non-null  object
 20  stop_auto_buy      1687860 non-null  object
 21  rev_stop           1687860 non-null  object
 22  went_on_backorder  1687860 non-null  object
dtypes: float64(15), object(8)
memory usage: 296.2+ MB

In [673]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier

# Transformações nas variáveis

## Retirando a variável sku

In [674]:
banco = banco.drop("sku", axis = 1)

banco.head()

,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,min_bank,potential_issue,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop,went_on_backorder
0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No,0.0,-99.00,-99.00,0.0,No,No,No,Yes,No,No
1,2.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No,0.0,0.99,0.99,0.0,No,No,No,Yes,No,No
2,2.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No,0.0,-99.00,-99.00,0.0,Yes,No,No,Yes,No,No
3,7.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,No,0.0,0.10,0.13,0.0,No,No,No,Yes,No,No
4,8.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,No,0.0,-99.00,-99.00,0.0,Yes,No,No,Yes,No,No

## Lidando com os valores NaN

- Nenhum ganho absurdo de diferença inputando a média, mediana ou moda (a mesma nos dá score parecidos)

In [675]:
banco.isnull().sum()

national_inv              1
lead_time            100894
in_transit_qty            1
forecast_3_month          1
forecast_6_month          1
forecast_9_month          1
sales_1_month             1
sales_3_month             1
sales_6_month             1
sales_9_month             1
min_bank                  1
potential_issue           1
pieces_past_due           1
perf_6_month_avg          1
perf_12_month_avg         1
local_bo_qty              1
deck_risk                 1
oe_constraint             1
ppap_risk                 1
stop_auto_buy             1
rev_stop                  1
went_on_backorder         1
dtype: int64

In [676]:
#--- Dropando todas

# banco = banco.dropna()

# banco.head()

In [677]:
# --- Comentar toda a célula é Ctrl + "/" do teclado numérico

#--- Excluindo a última linha e imputando média na variável lead_time

# (lembrar de desmarcar toda a vez)

# banco = banco[: -1] 

# banco["lead_time"] = banco["lead_time"].fillna(banco["lead_time"].mean())

In [678]:
#--- Excluindo a última linha e imputando média na variável lead_time

# (lembrar de desmarcar toda a vez)

# banco = banco[: -1] 

# banco["lead_time"] = banco["lead_time"].fillna(banco["lead_time"].median())

In [679]:
#--- Excluindo a última linha e imputando a moda na variável lead_time

# (lembrar de desmarcar toda a vez)

# banco = banco[: -1] 

# banco["lead_time"] = banco["lead_time"].fillna(banco["lead_time"].mode()[0])

In [680]:
#--- Excluindo a última linha e imputando o 0 na variável lead_time

# (lembrar de desmarcar toda a vez)

banco = banco[: -1] 

banco["lead_time"] = banco["lead_time"].fillna(0)

## Trocando as variáveis qualitativas para quantitativas

In [681]:
columns_yesno = ["potential_issue", "deck_risk", "oe_constraint", "ppap_risk", "stop_auto_buy", "rev_stop", "went_on_backorder"]

banco[columns_yesno] = banco[columns_yesno].replace({"No" : 0, "Yes": 1})

banco.head()

,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,min_bank,potential_issue,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop,went_on_backorder
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,-99.00,-99.00,0.0,0,0,0,1,0,0
1,2.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.99,0.99,0.0,0,0,0,1,0,0
2,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,-99.00,-99.00,0.0,1,0,0,1,0,0
3,7.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0.0,0.10,0.13,0.0,0,0,0,1,0,0
4,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,0,0.0,-99.00,-99.00,0.0,1,0,0,1,0,0

## Criando novas features

In [682]:
#--- Boa variável

banco["national_inv_poly2"] = banco["national_inv"] ** 2

#--- Variável ok

# banco["national_inv_qual"] = banco["national_inv"].map(lambda x: 0 if x < 0 else 1)

#--- 

# np.mean(banco["perf_6_month_avg"], banco["perf_12_month_avg"])

banco["perf_month_avg"] = banco[["perf_6_month_avg", "perf_12_month_avg"]].mean(axis=1)

## Separando em treino e teste

In [683]:
from sklearn.model_selection import train_test_split


x_treino, x_teste, y_treino, y_teste = train_test_split(banco.drop("went_on_backorder", axis = 1), banco["went_on_backorder"], train_size = 0.7, random_state = 1234, stratify = banco["went_on_backorder"])

In [684]:
print(x_treino.shape, y_treino.shape, x_teste.shape, y_teste.shape)

(1181502, 23) (1181502,) (506358, 23) (506358,)

In [685]:
print(15*"---")

print("Proporção da variável target nos dados de treino:\n", y_treino.value_counts(normalize = True))

print(15*"---")

print("Proporção da variável target nos dados de treino:\n", y_teste.value_counts(normalize = True))

---------------------------------------------
Proporção da variável target nos dados de treino:
 0    0.993309
1    0.006691
Name: went_on_backorder, dtype: float64
---------------------------------------------
Proporção da variável target nos dados de treino:
 0    0.993309
1    0.006691
Name: went_on_backorder, dtype: float64

In [686]:
from sklearn.utils import class_weight

class_weights1 = class_weight.compute_class_weight('balanced',
                                                 np.unique(y_treino),
                                                 y_treino)

class_weights1

array([ 0.50336785, 74.7313093 ])

In [687]:
dec_tree_cl = DecisionTreeClassifier(min_samples_leaf=5, 
                                     min_samples_split=5, 
                                     max_depth=None, 
                                     class_weight = {0: 0.51, 1: 72.34}, 
                                     random_state = 1234)

# Train Decision Tree Classifer
dec_tree_cl = dec_tree_cl.fit(x_treino, y_treino)

#Predict the response for test dataset
y_pred = dec_tree_cl.predict(x_teste)

#--- Considerações 

# 1. Quando utilizo o class_weight ele melhora significativamente a precion e recall
# 2. min_samples_leaf=2, min_samples_split=2, max_depth=None,class_weight = {0: 0.51, 1: 72.34} (1)

In [688]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_teste, y_pred)

print("Accuracy:", acc)

Accuracy: 0.9820897467799462

In [689]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_teste, y_pred))

[[495559   7411]
 [  1658   1730]]

In [690]:
pd.crosstab(y_teste, y_pred, rownames = ["True"], colnames = ["Predicted"], margins = True)

Predicted       0     1     All
True
0          495559  7411  502970
1            1658  1730    3388
All        497217  9141  506358

In [691]:
from sklearn.metrics import classification_report

print(classification_report(y_teste, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99    502970
           1       0.19      0.51      0.28      3388

    accuracy                           0.98    506358
   macro avg       0.59      0.75      0.63    506358
weighted avg       0.99      0.98      0.99    506358

In [692]:
pd.DataFrame(dec_tree_cl.feature_importances_, x_teste.columns).reset_index().rename(columns = {0: "Valor", "index": "Variável"}).sort_values("Valor", ascending = False).round(5)

              Variável    Valor
3     forecast_3_month  0.35459
0         national_inv  0.18451
6        sales_1_month  0.05774
22      perf_month_avg  0.04575
21  national_inv_poly2  0.04555
5     forecast_9_month  0.03657
9        sales_9_month  0.03620
14   perf_12_month_avg  0.03560
8        sales_6_month  0.03419
13    perf_6_month_avg  0.03211
1            lead_time  0.02625
7        sales_3_month  0.02601
10            min_bank  0.02291
4     forecast_6_month  0.02003
2       in_transit_qty  0.01983
16           deck_risk  0.00765
18           ppap_risk  0.00625
15        local_bo_qty  0.00383
19       stop_auto_buy  0.00216
12     pieces_past_due  0.00191
11     potential_issue  0.00021
20            rev_stop  0.00014
17       oe_constraint  0.00001

# Próximos passos:

1. Criar novas features
2. Observar as variáveis national_inv e lead_time
3. Testar o método de oversampling e undersampling